# Generated by Django 3.2.4 on 2021-07-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp4', '0002_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
